### ISSUE TITLE
After formatting the code, go back to the place where you edited the code

### ISSUE THREAD

**Issue by sq800** [Lixfeld/VS-FormatXaml-Extension#1]
After formatting the code, go back to the place where you edited the code。
The current situation is that it always returns to the first line of code every time

**Comment by Lixfeld** [comment]
Thanks for the feedback @sq800 I fixed this issue in the new version (1.0.1).
You can find the updated extension (vsix) under GitHub releases:
https://github.com/Lixfeld/VS-FormatXaml-Extension/releases/tag/v1.0.1

I will publish the changes to the marketplace in the next days, if everything works as expected.

**Comment by sq800** [comment]
Thanks for your work!
